### ISSUE TITLE
transaction counter

### ISSUE THREAD

**Issue by jani8x** [LiskHQ/lisk-explorer#12]
Please put numbers on transactions on top as well. I can see whole amount, but can't count transactions.

Like here: https://explorer.lisk.io/address/6300322192409448238L

**Comment by Isabello** [comment]
This one might be a challenge to implement since we don't have an endpoint to return a count of all tx an address has been a part of. We can enumerate the list but in general we limit tx returns to 100 at a time, as evidenced here by getTransactionsByAddress

https://github.com/LiskHQ/lisk-explorer/blob/18e5ecbebd180be65579bdc39cdceb9a80588e47/lib/api/transactions.js#L77

```
            url : app.get('lisk address') + '/api/transactions?recipientId=' + query.address + '&senderId=' + query.address + '&orderBy=timestamp:desc' + '&offset=' + param(query.offset, 0) + '&limit=' + param(query.limit, 100),
```

We could do a one time query to pull back all transactions but thats very heavy. To go forward with this i recommend we implement a new endpoint on #liskhq/lisk

**Comment by Isabello** [comment]
wrong button :)
