### ISSUE TITLE
Migrate from ES2015 to ES2016

### ISSUE THREAD

**Issue by alihaghighatkhah** [LiskHQ/lisk-explorer#136]
Current state:
 - JavaScript code is written in ES5

Expected state:
 - Should be written in ES2016

**Comment by alihaghighatkhah** [comment]
Prerequisites for initial transforms according to [Lebab](https://www.npmjs.com/package/lebab#safe-transforms):
 - `var` to `let` / `const`.
 - `for` loops over array to `for-of`.
 - arrow functions:
   - Use function in the global scope and for Object.prototype properties.
   - Use class for object constructors.
   - Use => everywhere else.
 - add grunt babel transpiler

**Comment by mrv777** [comment]
Just my opinion :)
Changing var to let and const has a functional purpose.
While arrow functions are really just cosmetic and for look...and I don't like them :)  It's too easy to make the code more confusing.  I prefer named functions everywhere instead of the shorthand arrow function.  Named functions make it easier to debug issues :)

**Comment by Isabello** [comment]
Closed via #157
