### ISSUE TITLE
delegateMonitor table sorting

### ISSUE THREAD

**Issue by Doweig** [LiskHQ/lisk-explorer#16]
The table sorting on the "Forged" column is not sorting correctly (see screenshot)

![screen shot 2016-10-04 at 12 28 42 pm](https://cloud.githubusercontent.com/assets/1850848/19062620/45e35d74-8a2e-11e6-9e97-ef987e40dcad.png)

This seems to come from the fact that the cell values are processed as strings and not numbers.

Given the input: 8895, 690, 5299
Alphabetical order (strings): 5299 > 690 > 8895
Ascending order (numbers): 690 > 5299 > 8895

**Comment by Isabello** [comment]
Like @Doweig this is related to forged LSK returning as a string.

Here is the line where we grab forged lisk and pass it to the filter

https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/delegateMonitor.html#L266
`<td class="hidden-xs hidden-sm">{{d.forged | lisk}} <span class="text-muted">LSK</span></td>`

Next up is the filter itself. Its written to convert the string to an Int and adjust the decimal place. It is then returned as a String, which is what the sorting is occuring in a string like fashion. Converting the number to a float does not help as it just continues to pass back as a string.
https://github.com/LiskHQ/lisk-explorer/blob/development/public/src/js/filters.js#L83
````
  .filter('lisk', function () {
      return function (amount) {
          if (isNaN(amount)) {
              return (0).toFixed(8);
          } else {
              return (parseInt(amount) / 100000000);
          }
      };
  })
```

This can most likely be addressed by creating a function for sorting rather than relying on the following orderBy function.

https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/delegateMonitor.html#L262

` <tr data-ng-repeat='d in activeDelegates | orderBy:tables.active.predicate:tables.active.reverse track by d.rate'>`

**Comment by Isabello** [comment]
This issue is resolved but there is a new one replacing it for the status column not sorting at all.

**Comment by karmacoma** [comment]
@Isabello: I've fixed the "Status" column ordering: https://github.com/LiskHQ/lisk-explorer/commit/aec1f9138e3f8dcf90fe3067ff55c561d89c6489

**Comment by Isabello** [comment]
Completely resolved by @karmacoma commit: https://github.com/LiskHQ/lisk-explorer/commit/aec1f9138e3f8dcf90fe3067ff55c561d89c6489
