### ISSUE TITLE
Network Monitor - Incorrect platforms counter

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk-explorer#17]
A user reported running a mac and be detected as a mac.
Count is still 0.
1 picture worth a thousand words.

![clipboard](https://cloud.githubusercontent.com/assets/18356726/19953478/a6f1dc3a-a144-11e6-974b-3f1000dd4391.png)

**Comment by Isabello** [comment]
I found the source of this bug and have tested a fix. I also removed windows as part of the fix since we do not support that platform

![image](https://cloud.githubusercontent.com/assets/16565680/19955933/7e2351b6-a154-11e6-8436-e5a2a7892c39.png)

to get FreeBSD to show we need to edit a few thing in statistics.js

https://github.com/LiskHQ/lisk-explorer/blob/development/lib/api/statistics.js#L266

This line to allow parsing for FreeBSD

Next, we need to edit the HTML that sites on the networkMonitor.html page

https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/networkMonitor.html#L129

Change these entries to read FreeBSD

Finally, we need to edit some logic for networkMonitor.js. we swap out windows for FreeBSD here.

https://github.com/LiskHQ/lisk-explorer/blob/development/public/src/js/services/networkMonitor.js#L8

As for Darwin itself, the way the counters are populated comes from lisk-core. We read the actively connected peers list to populate these counters, not the database. So in the very rare chance that the explorer connects to a OSX node it will display, but only while the counter data is in memory. Im not sure what we can do about this, but we can definitely improve how this works eventually.

**Comment by Gr33nDrag0n69** [comment]
Reading the bug list again, this might be same bug : https://github.com/LiskHQ/lisk-explorer/issues/2

**Comment by Isabello** [comment]
It is. I didnt mark it yet

**Comment by Isabello** [comment]
closed by: https://github.com/LiskHQ/lisk-explorer/commit/f253d0315a9f2b5840b6fcfb384f33afacfa1cf6
