### ISSUE TITLE
feature https://explorer.lisk.io

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-explorer#229]
Its so convenient to get an email notification if your lisk wallet receives a payment like can be done on https://etherscan.io/ (here you can choose any public key to be notified, but my personal public key would be a great first step for the lisk explorer) Can this be done on https://explorer.lisk.io ?

**Comment by Isabello** [comment]
While its nice, it will not be implemented into explorer due to the issues around DKIM and other aspects of mail configuration that can create security holes for operators.

**Comment by 4miners** [comment]
I don't see security risk here, it's node operator responsibility to configure mail server properly.
- Enable support for notifications should be optional.
- We should allow send notifications via local or external mail server. 
- Because is currently not possible to login to explorer with account - we can implement simple log in using sign/verify message (if we only allow to send notifications only for own accounts) and store session in cookies or browser storage.

**Comment by Joo5t** [comment]
There is a community solution launched ! https://notifications.lisk.rocks/ 
I now receive email notifitcations when sending/receiving Lisk from my wallet 👍
