### ISSUE TITLE
Fix market watcher candles endpoints

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-explorer#368]
### Expected behaviour
Candles should return the market data continuously without any frequent errors.

### Actual behaviour
Currently the endpoints don't respond as expected in frequent time ranges.

### Steps to reproduce
Navigate to `/marketWatcher`

**Comment by MichalTuleja** [comment]
The Bittrex API has changed breaking the previous method, but there are two solutions available:
- using the version 1.1, which provides us only recent data.
The response is limited to last 100 results which is approx. 1 minute behind. In this case, the format of data is the same as version 1.0, but the backend process can be designed in order to collect historical data making the candlestick chart useful.

- using the version 2.0, that provides the data in different format.
That solution relies on the not officially documented version 2.0 of API. The data for candlesticks are already provided by the API which requires also change to the logic in the market watcher code.

I've decided to implement the second solution, while despite the difference in the data structure it provides us whole dataset at one request.

The HTTP request to the 2.0 API:
``
https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-LSK&tickInterval=fiveMin
``
