### ISSUE TITLE
Remove state 0 peers data from networkMonitor counters

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk-explorer#37]
Currently state 0 peers data makes its way into the counters, leaving a misleading representation of the actual network landscape.

We already remove peers from the map here: https://github.com/LiskHQ/lisk-explorer/blob/development/public/src/js/services/networkMonitor.js#L209 but we don't remove disconnected peers from the other counters.

In order to make the display of height, version and platforms  accurate we need to remove disconnected peers from their counters.

**Comment by 4miners** [comment]
Counters are based only on peers that we assume as connected, we do it here:
https://github.com/LiskHQ/lisk-explorer/blob/development/lib/api/statistics.js#L242

Peers with `state = 0` are banned peers, we currently assume them as connected if they have height, if they don't - we assume them as disconnected.
Peers with `state = 1` appear when initialised without state or just after ban is lifted - we assume them as disconnected.
Peers with `state = 2` are assumed as connected if they have height, if not - they are useless and we assume them as disconnected.

So we have currently some peers with green `V` icon and `Connected` status in `Disconnected Peers` tab and some peers without `V` or `X` icon in both tabs (banned peers). However only peers from `Connected Peers` tab are considered for counters.

Such assumptions were made because of https://github.com/LiskHQ/lisk/issues/334 - we currently need banned peers for complete network view. I propose suspend that issue now and review it after https://github.com/LiskHQ/lisk/issues/334 is resolved.

**Comment by 4miners** [comment]
Issue https://github.com/LiskHQ/lisk/issues/334 is resolved, but I still think that we need banned peers for complete network view. Let me know if you accept that @Isabello.

**Comment by Isabello** [comment]
All set.
